# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  watch:
    types: [started]
  

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: let's Run!
        id: request
        run: echo 'test'
      - name: run one more time
        id: getpip
        run: |
          echo 'second' |
          pip3 list
      - name: run node
        id: node
        run: |
          node --version
  second:
    runs-on: ubuntu-latest
    steps:
      - name: let's Run!
        id: test
        run: echo 'test'
      - name: run one more time
        id: second
        run: |
          echo 'second' |
          pip3 list
      - name: run node
        id: node
        run: |
          node --version
